using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Mediarq.SourceGenerators;

/// <summary>
/// Incremental source generator that discovers, at compile time, every Mediarq handler, pipeline
/// behavior and validator declared in the current assembly and emits an internal
/// <c>services.AddMediarqHandlers()</c> extension that registers them explicitly.
/// This removes the runtime, reflection-based assembly scan and is trimming/AOT friendly.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class MediarqRegistrationGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FullyQualified = SymbolDisplayFormat.FullyQualifiedFormat;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registrations = context.CompilationProvider.Select(static (compilation, _) => GetRegistrations(compilation));
        context.RegisterSourceOutput(registrations, static (spc, lines) => Emit(spc, lines));
    }

    private static List<string> GetRegistrations(Compilation compilation)
    {
        var lines = new List<string>();
        var seen = new HashSet<string>();

        foreach (var type in EnumerateTypes(compilation.Assembly.GlobalNamespace))
        {
            if (type.TypeKind != TypeKind.Class || type.IsAbstract || type.IsStatic)
                continue;

            if (type.DeclaredAccessibility != Accessibility.Public && type.DeclaredAccessibility != Accessibility.Internal)
                continue;

            var ns = type.ContainingNamespace?.ToDisplayString() ?? string.Empty;
            if (ns == "Mediarq.Core" || ns.StartsWith("Mediarq.Core."))
                continue;

            foreach (var iface in type.AllInterfaces)
            {
                var definition = iface.OriginalDefinition;
                var key = definition.ContainingNamespace.ToDisplayString() + "." + definition.MetadataName;
                if (!IsTarget(key))
                    continue;

                string line;
                if (type.IsGenericType)
                {
                    var service = definition.ConstructUnboundGenericType().ToDisplayString(FullyQualified);
                    var impl = type.ConstructUnboundGenericType().ToDisplayString(FullyQualified);
                    line = "            services.AddScoped(typeof(" + service + "), typeof(" + impl + "));";
                }
                else
                {
                    var service = iface.ToDisplayString(FullyQualified);
                    var impl = type.ToDisplayString(FullyQualified);
                    line = "            services.AddScoped<" + service + ", " + impl + ">();";
                }

                if (seen.Add(line))
                    lines.Add(line);
            }
        }

        lines.Sort(System.StringComparer.Ordinal);
        return lines;
    }

    private static bool IsTarget(string key) =>
        key == "Mediarq.Core.Common.Requests.Abstraction.IRequestHandler`2" ||
        key == "Mediarq.Core.Common.Requests.Notifications.INotificationHandler`1" ||
        key == "Mediarq.Core.Common.Pipeline.IPipelineBehavior`2" ||
        key == "Mediarq.Core.Common.Requests.Validators.IValidator`1";

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol root)
    {
        var stack = new Stack<INamespaceSymbol>();
        stack.Push(root);

        while (stack.Count > 0)
        {
            var ns = stack.Pop();
            foreach (var member in ns.GetMembers())
            {
                if (member is INamespaceSymbol childNamespace)
                {
                    stack.Push(childNamespace);
                }
                else if (member is INamedTypeSymbol type)
                {
                    yield return type;
                }
            }
        }
    }

    private static void Emit(SourceProductionContext context, List<string> registrations)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Mediarq.Extensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Compile-time generated Mediarq handler, behavior and validator registrations.</summary>");
        sb.AppendLine("    internal static class MediarqGeneratedRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers every Mediarq handler, behavior and validator discovered at compile time.</summary>");
        sb.AppendLine("        internal static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMediarqHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        foreach (var line in registrations)
        {
            sb.AppendLine(line);
        }
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("MediarqGeneratedRegistration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
